import type { Metadata } from "next";
import "./globals.css";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import Header from "@/components/header/Header";
// import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Amazon Clone || Multiple Products",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" font-bodyFont">
        <Header />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
